# Generated by Django 4.2.20 on 2025-05-01 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bid',
            new_name='bids',
        ),
        migrations.RenameModel(
            old_name='comment',
            new_name='comments',
        ),
    ]
