# Generated by Django 4.2.20 on 2025-05-01 21:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_bid_bids_rename_comment_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
